"""One-shot helper: fetch upstream SKILL.md frontmatter and emit starter YAML
for the legal-services manifest skills block.

Usage:
    python -m scripts.extract_upstream_metadata > /tmp/skills-block.yaml

Then review and paste into manifest.yaml. NOT run by `make build`.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys

import yaml

from scripts.build import fetch_upstream_file


UPSTREAM_REPO = "anthropics/claude-for-legal"
UPSTREAM_COMMIT = "9cecd91b0f26f732d18315afc3c9bb5ff99e0fbb"

PLUGINS = [
    "commercial-legal",
    "corporate-legal",
    "employment-legal",
    "privacy-legal",
    "product-legal",
    "regulatory-legal",
    "ai-governance-legal",
    "ip-legal",
    "litigation-legal",
    "law-student",
    "legal-clinic",
    "legal-builder-hub",
]


def list_plugin_skills(plugin: str) -> list[str]:
    """Return the bare skill slugs (subdirs of <plugin>/skills/) for one plugin.

    Plugin slugs are alphanumeric + single dashes; no regex escaping needed
    (jq's regex flavor rejects `\\-` which is what `re.escape` emits).
    """
    out = subprocess.run(
        [
            "gh", "api",
            f"repos/{UPSTREAM_REPO}/git/trees/{UPSTREAM_COMMIT}?recursive=1",
            "--jq",
            f'.tree[] | select(.path | test("^{plugin}/skills/[^/]+/SKILL\\\\.md$")) | .path',
        ],
        check=True, capture_output=True, text=True,
    )
    skills = []
    for line in out.stdout.splitlines():
        parts = line.split("/")  # plugin/skills/<bare>/SKILL.md
        skills.append(parts[2])
    return sorted(skills)


# Word-level overrides applied after kebab → Title Case. Keys are lowercase
# tokens produced by the split; values are the desired display form.
TITLE_OVERRIDES = {
    "ai": "AI",
    "aia": "AIA",
    "dpa": "DPA",
    "dsar": "DSAR",
    "fto": "FTO",
    "ip": "IP",
    "irac": "IRAC",
    "msa": "MSA",
    "nda": "NDA",
    "oc": "OC",
    "oss": "OSS",
    "pia": "PIA",
    "qa": "Q&A",
    "saas": "SaaS",
}


def title_from_slug(slug: str) -> str:
    """Convert kebab-case to Title Case with legal/tech acronym overrides."""
    tokens = slug.split("-")
    return " ".join(TITLE_OVERRIDES.get(tok, tok.capitalize()) for tok in tokens)


def first_sentence(description: str) -> str:
    """Return the first sentence of a multi-line description string, trimmed."""
    flat = " ".join(description.split())
    m = re.match(r"^(.+?[.!?])(?:\s|$)", flat)
    return (m.group(1) if m else flat).strip()


def extract_skill_metadata(plugin: str, bare: str) -> tuple[str, str]:
    """Fetch <plugin>/skills/<bare>/SKILL.md and return (display_name, description)."""
    path = f"{plugin}/skills/{bare}/SKILL.md"
    content = fetch_upstream_file(UPSTREAM_REPO, UPSTREAM_COMMIT, path).decode("utf-8")
    if not content.startswith("---\n"):
        return title_from_slug(bare), f"Upstream skill at {path}."
    end = content.find("\n---\n", 4)
    fm = yaml.safe_load(content[4:end]) or {}
    raw_desc = fm.get("description", "") or ""
    return title_from_slug(bare), first_sentence(raw_desc)


def main() -> int:
    lines: list[str] = [
        "# Generated by scripts/extract_upstream_metadata.py — review before committing."
    ]
    for plugin in PLUGINS:
        bare_slugs = list_plugin_skills(plugin)
        print(f"# {plugin}: {len(bare_slugs)} skills", file=sys.stderr)
        for bare in bare_slugs:
            slug = f"{plugin}--{bare}"
            name, desc = extract_skill_metadata(plugin, bare)
            # JSON-quoted strings are valid single-line YAML scalars; avoids
            # safe_dump's document-end marker and multi-line continuation noise.
            lines.append(f"  {slug}:")
            lines.append(f"    name: {json.dumps(name, ensure_ascii=False)}")
            lines.append(f"    description: {json.dumps(desc, ensure_ascii=False)}")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
